Add Restart=on-failure to gitlab-exporter service
The gitlab-exporter service occasionally fails with errors like:

  Error: missing: `response data`
  Caused by: MissingData("response data")

Let's see if restarting it on errors automatically helps avoid this.